export default [
  {
    id: 21,
    title: "İtalyan Papadias",
    price: 8,
    desc: "Pizza Sousu, İtalyan Sosisi, Pepperoni, Mozzarella, Parmezan, Italyan ədviyyatları",
    img: "https://www.papajohns.az/uploads/images/Papadias/%C4%B0talyan-papadias.png",
    quantity: 1,
  },
  {
    id: 22,
    title: "Çeddar Meksika Papadias",
    price: 8,
    desc: "Pizza sousu, Yaşıl Bibər, Qril Toyuğu, Mozzarella, Halapeno",
    img: "https://www.papajohns.az/uploads/images/Papadias/Cheddar-Mexican-Papadias-yeni-sayt.png",
    quantity: 1,
  },
  {
    id: 23,
    title: "Dabl Çeddar Çizburger Papadias",
    price: 8,
    desc: "1000 Ada sousu, Mal Əti, Pomidor, Mozzarella və Cheddar Pendirləri",
    img: "https://www.papajohns.az/uploads/images/Papadias/Dabl-cheddar-%C3%A7%C4%B0zburger-Papad%C4%B0as-yeni-sayt.png",
    quantity: 1,
  },
  {
    id: 24,
    title: "Nyu Orleans Papadias",
    price: 11,
    desc: "Sarımsaq Sousu, Yaşıl Bibər, Qril Toyuğu, Qarğıdalı, Mozzarella Pendiri. ",
    img: "https://www.papajohns.az/uploads/images/Papadias/Nyu-Orleans-papad%C4%B0as-yeni-sayt.png",
    quantity: 1,
  },
  {
    id: 25,
    title: "Çiken Baffalo Papadias",
    price: 21,
    desc: "Ranç Sousu, Qril Toyuq, Pomidor, Mozzarella Pendiri, Baffalo Sousu",
    img: "https://www.papajohns.az/uploads/images/Papadias/Buffalo-Chiken-Papadias.jpg",
    quantity: 1,
  },
  {
    id: 26,
    title: "Acılı Çiken Ranç Papadias",
    price: 16,
    desc: "Ranç Sousu, Qril Toyuğu, Göbələk, Pomidor, Halapeno, Mozarella",
    img: "https://www.papajohns.az/uploads/images/Papadias/Acili-%C3%A7iken-ran%C3%A7-papadias.png",
    quantity: 1,
  },
  {
    id: 27,
    title: "Çiken BBQ Papadias",
    price: 20,
    desc: "Qril Toyuğu, Göbələk, Mozzarella, Barbekyu sousu",
    img: "https://www.papajohns.az/uploads/images/Papadias/%C3%87iken-BBQ-Papadias.png",
    quantity: 1,
  },
];
