export default [
  {
    id: 1,
    title: "Qril Çiken Parmezan",
    price: 5.5,
    describtion:
      "Sarımsaqlı Parmezan sousu, Qril Toyuğu, Vetçina, Pomidor, Mozzarella Pendiri, Halapeno Bibəri",
    img: "https://www.papajohns.az/uploads/images/pizza/Grill-%C3%87iken-Parmezan.png",
    quantity: 1,
  },
  {
    id: 2,
    title: "Amerikan Hot",
    price: 12.5,
    describtion: "Pizza Sous, Mozzarella pendiri, Pepperoni və Halapeno Bibəri",
    img: "https://www.papajohns.az/uploads/images/pizza/american-hot.png",
    quantity: 1,
  },
  {
    id: 3,
    title: "Acılı Çiken Ranç",
    price: 16,
    describtion:
      "Ranç Sousu, Toyuq Əti, Göbələklər,  Halapeno Bibəri, Təzə Doğranmış Pomidorlar və Mozzarella Pendiri",
    img: "https://www.papajohns.az/uploads/images/pizza/Spicy-chicken-ranch.png",
    quantity: 1,
  },
  {
    id: 4,
    title: "Karnaval",
    price: 17,
    describtion: "Pizza Sous, Göbələk, Qara Zeytun, Pepperoni, Mozzarella ",
    img: "https://www.papajohns.az/uploads/images/pizza/Karnaval.jpg",
    quantity: 1,
  },
  {
    id: 5,
    title: "New York Style Marqarita (40 sm)",
    price: 21,
    describtion: "Pizza Sous, Mozzarella, Pomidor, Oreqano",
    img: "https://www.papajohns.az/uploads/images/pizza/New-York-Style-Margarita.jpg",
    quantity: 1,
  },
  {
    id: 6,
    title: "New York Style Qril Çiken (40 sm)",
    price: 26,
    describtion: "Pizza Sous, Qril Toyuğu, Mozzarella Pendiri, Pomidor",
    img: "https://www.papajohns.az/uploads/images/pizza/New-York-Style-Grill-Chiken.jpg",
    quantity: 1,
  },
  {
    id: 7,
    title: "Papa Miks",
    price: 20,
    describtion: "Çiken BBQ, Hot&Spaysi, Marqarita, Klassik Pepperoni",
    img: "https://www.papajohns.az/uploads/images/pizza/papamiks-sayt.png",
    quantity: 1,
  },
  {
    id: 8,
    title: "Cheddar Dabl Burger",
    price: 12,
    describtion: "1000 ada sousu, Mal əti, Pomidor, Mozzarella, Cheddar",
    img: "https://www.papajohns.az/uploads/images/pizza/Cheddar-Dabl-Burger.png",
    quantity: 1,
  },
  {
    id: 9,
    title: "Çiken Barbekyu",
    price: 18,
    describtion: "Qril Toyuq, Göbələk, Barbekyu Sousu, Mozzarella Pendiri",
    img: "https://www.papajohns.az/uploads/images/chicken_barbekyu.jpg",
    quantity: 1,
  },
  {
    id: 10,
    title: "Hot and Spaysi",
    price: 21,
    describtion:
      "Mal Əti, Pomidor, Yaşıl Bibər, Halapeno Bibəri, Mozzarella Pendiri",
    img: "https://www.papajohns.az/uploads/images/hot_and_spaysi.jpg",
    quantity: 1,
  },
  {
    id: 11,
    title: "Cheddar Çiken Club",
    price: 11,
    describtion:
      "Qril toyuğu, Pomidor, Vetçina, Mozzarella, Cheddar, Ranç sousu",
    img: "https://www.papajohns.az/uploads/images/pizza/Cheddar-%C3%87iken-Club.png",
    quantity: 1,
  },
  {
    id: 12,
    title: "Meksika",
    price: 15,
    describtion:
      "Qril Toyuq, Pomidor, Göbələk, Yaşıl Bibər, Halapeno Bibəri, Mozzarella Pendiri",
    img: "https://www.papajohns.az/uploads/images/meksika.jpg",
    quantity: 1,
  },
];
